version: 2

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

job_defaults: &job_defaults
  working_directory: /go/src/github.com/hamakn/go_ddd_webapp
  docker:
    - image: mercari/appengine-go:1.9

jobs:
  test:
    <<: *job_defaults
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u golang.org/x/lint/golint
      - run: go get -u github.com/daisuzu/gsc
      - run: dep ensure -vendor-only
      - type: cache-save
        key: dep-cache-{{ checksum "Gopkg.lock" }}
        paths:
          - vendor
      - run: golint -set_exit_status ./config... && golint -set_exit_status ./src/...
      - run: RESULT=$(gofmt -d -s ./config/ ./src/) && echo "${RESULT}"; ! [ -n "${RESULT}" ]
      - run: go vet ./config/... ./src/...
      - run: gsc -tests=false ./config/... ./src/...
      - run: goapp test ./config/... ./src/...

  deploy:
    <<: *job_defaults
    steps:
      - checkout
      - type: cache-restore
        key: dep-cache-{{ checksum "Gopkg.lock" }}
      - run: ./bin/ci/deploy
